### ISSUE TITLE
Can't perform this action after onSaveInstanceState

### ISSUE THREAD

**Issue by chnouman** [tunjid/Android-Extensions#7]
```
java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
        at androidx.fragment.app.FragmentManager.checkStateLoss(FragmentManager.java:1689)
        at androidx.fragment.app.FragmentManager.enqueueAction(FragmentManager.java:1729)
        at androidx.fragment.app.BackStackRecord.commitInternal(BackStackRecord.java:321)
        at androidx.fragment.app.BackStackRecord.commit(BackStackRecord.java:286)
        at com.emaar.shopndrop.navigation.MultiStackNavigator.showInternal(MultiStackNavigator.kt:320)
        at com.emaar.shopndrop.navigation.MultiStackNavigator.show(MultiStackNavigator.kt:119)
        at com.emaar.shopndrop.activities.MainActivity$fetchRequestDetail$1.onNext(MainActivity.kt:193)
        at com.emaar.shopndrop.activities.MainActivity$fetchRequestDetail$1.onNext(MainActivity.kt:178)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(ObservableObserveOn.java:201)
        at io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(ObservableObserveOn.java:255)
        at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:124)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

```

@tunjid  I'm getting this error. What I'm trying is after launching MainActivity hitting the web API and launching fragment.

**Comment by chnouman** [comment]
I get it it was my bad.

**Comment by guyaumetremblay** [comment]
@chnouman I get the same error, could you explain what was the reason on your side please?

**Comment by chnouman** [comment]
@guyaumetremblay sorry buddy I can't remember what exactly was the problem.

**Comment by tunjid** [comment]
@guyaumetremblay in what scenarios do you get it?

**Comment by guyaumetremblay** [comment]
@tunjid I just found this: https://stackoverflow.com/a/10261449

I do have a `onSaveInstanceState` which add something in the outState after calling `super`. As I understand the accepted answer on the SO thread, the exception is happening because MultiStackNavigator is calling `fragmentManager.commit` instead of `commitAllowingStateLoss`.

We'll try to fix our `onSaveInstanceState` as I don't think changing from `commit` to `commitAllowingStateLoss` on your side is a proper solution!
